FROM openjdk:8 AS BUILD_IMAGE
#Build description
ENV APP_HOME=/usr/plant-grow
WORKDIR $APP_HOME
ADD --chown=1000:1000 . .
RUN ./gradlew build -x test

FROM openjdk:8-jre-alpine
#Runtime description
COPY --from=BUILD_IMAGE /usr/plant-grow/build/libs/plant-grow-server-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
USER 1000
CMD ["java", "-jar", "plant-grow-server-0.0.1-SNAPSHOT.jar", "com.rasp.server.ServerApplication"]